name: Build LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build PDF (latexmk + biber via texlive-full)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/main.tex
          # Usa imagem com TeX Live Full (inclui biber)
          docker_image: ghcr.io/xu-cheng/texlive-full:latest
          latexmk_use_lualatex: false
          # Se usar fontes/shell-escape em figuras TikZ, habilite:
          # latexmk_shell_escape: true

      - name: Upload artifact (main.pdf)
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: src/main.pdf

