name: Build LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup TeX Live (full)
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >
            scheme-full

      - name: Install biber
        run: sudo apt-get update && sudo apt-get install -y biber

      - name: Build PDF with latexmk
        working-directory: src
        run: |
          latexmk -pdf -interaction=nonstopmode main.tex
          ls -lh main.pdf

      - name: Upload artifact (main.pdf)
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: src/main.pdf

