name: Release PDF

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build PDF (latexmk + biber via texlive-full)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/main.tex
          docker_image: ghcr.io/xu-cheng/texlive-full:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/main.pdf

