name: Release PDF

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >
            scheme-full

      - name: Install biber
        run: sudo apt-get update && sudo apt-get install -y biber

      - name: Build PDF
        working-directory: src
        run: latexmk -pdf -interaction=nonstopmode main.tex

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/main.pdf

